language: python
python:
  - "3.6"
  - "nightly"
install:
  - pip install https://github.com/yaml/pyyaml/archive/master.zip
  - pip install coverage
  - pip install python-coveralls
script:
  - python -m coverage run runtests.py
after_script:
  - coveralls
